balance_loss: True
model_config:
  abmil:
    feat_ext_name: 'fc_1_512'
    pool_att_dim: 128
  transformer_abmil:
    feat_ext_name: 'fc_1_512'
    pool_att_dim: 128
    transf_att_dim: 512
    transf_num_heads: 8
    transf_num_layers: 2
    transf_use_ff: False
    transf_dropout: 0.0
    transf_add_self: True
  sm_abmil:
    feat_ext_name: 'fc_1_512'
    pool_att_dim: 128
    sm_alpha: 'trainable'
    sm_mode: 'approx'
    sm_steps: 10
    sm_where: 'mid'
    sm_spectral_norm: True  
  sm_transformer_abmil:
    feat_ext_name: 'fc_1_512'
    pool_att_dim: 128
    transf_att_dim: 512
    transf_num_heads: 8
    transf_num_layers: 3
    transf_use_ff: True
    transf_dropout: 0.0
    transf_add_self: False
    sm_alpha: 'trainable'
    sm_mode: 'approx'
    sm_steps: 10
    sm_where: 'mid'
    sm_transformer: True
    sm_spectral_norm: True
  bayes_smooth_abmil:
    feat_ext_name: 'fc_1_512'
    pool_att_dim: 128
    covar_mode: 'diag'
    annealing_epochs_per_cycle: 20
    annealing_cycle_prop: 0.8
    annealing_warmup_cycles: 0
    annealing_min_coef: 0.0
    annealing_max_coef: 1.0
  transformer_bayes_smooth_abmil:
    feat_ext_name: 'fc_1_512'
    pool_att_dim: 128
    transf_att_dim: 512
    transf_num_heads: 8
    transf_num_layers: 2
    transf_use_ff: False
    transf_dropout: 0.0
    transf_add_self: True
    covar_mode: 'diag'
    annealing_epochs_per_cycle: 20
    annealing_cycle_prop: 0.8
    annealing_warmup_cycles: 0
    annealing_min_coef: 0.0
    annealing_max_coef: 1.0
  transmil:
    emb_dim: 512
    att_dim: 512
    num_heads: 8
  camil:
    emb_dim: 512
    att_dim: 512
    num_heads: 8
  gtp:
    num_layers: 2
    embed_dim: 512
    num_heads: 4
    node_cluster_num: 50
  setmil:
    embed_dim: 128
    token_dim: 256
    depth: 2
    num_heads: 4
    drop_rate: 0.1
    attn_drop_rate: 0.1
    drop_path_rate: 0.1
    mlp_ratio: 1.0
    qkv_bias: False
    qk_scale: nonlinear
    aspp_flag: transf_use_ff
    max_token_num: 5000
  iibmil:
    emb_dim: 512
    depth_encoder: 1
    depth_decoder: 1
    num_queries: 5
  dsmil:
    feat_ext_name: 'fc_1_512'
    att_dim: 128
    nonlinear: True
    passing_v: False
  clam:
    feat_ext_name: 'fc_1_512'
    att_dim: 128
    dropout: 0.0
    k_sample: 10
    instance_loss_name: 'svm'
  dftdmil:
    feat_ext_name: 'fc_1_512'
    att_dim: 128
    num_groups: 4
    distill: 'maxmin'
  pathgcn:
    num_layers: 3
    resample: 0.0
    hidden_dim: 512
    att_dim: 128
  deepgraphsurv:
    num_layers: 3
    resample: 0.0
    hidden_dim: 512
    att_dim: 128



