site_name: torchmil
site_description: Documentation for the torchmil package.
site_author: Fran Castro
site_url: 

repo_url: https://github.com/Franblueee/torchmil
repo_name: Franblueee/torchmil
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

theme:
  name: material
  features:
    - navigation.sections  # Sections are included in the navigation on the left.
    - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
    - header.autohide  # header disappears as you scroll
  palette:
    # Light mode / dark mode
    # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
    # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
    - scheme: default
      primary: white
      accent: amber
      toggle:
          icon: material/weather-night
          name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
          icon: material/weather-sunny
          name: Switch to light mode
  icon:
    repo: fontawesome/brands/github  # GitHub logo in top right
    logo: "material/abacus"  # Equinox logo in top left

  favicon: "_static/abacus.png"
  custom_dir: "docs/_overrides"  # Overriding part of the HTML

  twitter_name: "@Franblueee"
  twitter_url: "https://x.com/franblueee"

strict: True

extra_javascript: 
    # The below two make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - _static/custom_css.css

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        # permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4

plugins:
  - search  # default search plugin; needs manually re-enabling when using any other plugins
  - autorefs  # Cross-links to headings
  # - mknotebooks  # Jupyter notebooks
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          # setup_commands:
          #   - import pytkdocs_tweaks
          #   - pytkdocs_tweaks.main()
          #   - import jaxtyping
          #   - jaxtyping.set_array_name_format("array")
          #   - import jax
          #   - import jax.extend.core
          #   - jax.ShapeDtypeStruct.__module__ = "jax"
          #   - jax.extend.core.ClosedJaxpr.__module__ = "jax.extend.core"
          options:
            show_source: false  # don't include source code
            show_bases: true
            show_root_heading: true  
            show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
            inherited_members: true  # Allow looking up inherited methods
            show_if_no_docstring: false
            show_signature_annotations: false
            members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
            heading_level: 4
            docstring_section_style: list

nav:
  - index.md
  - Models:
      - Modules:
          - models/modules/attention_pool.md
      - models/ABMIL.md
      - models/SmABMIL.md
      - models/ProbSmoothABMIL.md