name: Build docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
   
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mknotebooks mkdocstrings mkdocstrings-python mkdocs-exclude
      - run: mkdocs gh-deploy --clean
