name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-test:
    strategy:
      matrix:
        # must match the `language_version` in `.pre-commit-config.yaml`
        python-version: [ 3.11 ]
        os: [ ubuntu-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install .[dev]
          python -m pip install .[tests]

        
      - name: Checks with pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Test with pytest
        run: |
          python -m pytest --cov=./torchmil --cov-report=xml
      
      - name: Display coverage.xml content
        run: |
          cat ./coverage.xml
          
      - name: Upload coverage to Codecov
        # Use the codecov-action to upload the generated coverage.xml
        uses: codecov/codecov-action@v4
        with:
          # Specify the path to your coverage XML report
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
